### PR TITLE
Remove css reset, close #13

### LINKED ISSUE #13: Get rid of CSS reset
CSS resets generally aren't necessary anymore for modern browsers. We really don't even normalize [these days](https://css-tricks.com/normalize-css-no/), but the goal for this issue is to use Tachyons in the most default way possible, which means including the packaged copy of normalize.

The Kaldi template currently relies on the CSS reset - swapping it for normalize does funky things in the layout for things like list items and links. Completing this issue will require a thorough check of resulting styles across browsers and breakpoints.

### PR DESCRIPTION
**Pull request by covingtondoan**

### CODE REVIEW

**Comment by covingtondoan** [comment]
I also noticed that the straight quotes were not converted to "smart quotes".

**Comment by erquhart** [comment]
Thanks for this! We'll have a look soon.

**Comment by erquhart** [comment]
Again, apologies for the delay - I see no breaks in the layout, looks great! The only thing still needed is removal of the reset file itself, then we can merge.

**Comment by covingtondoan** [comment]
@erquhart I've removed the reset files itself. Good to merge?

**Pull request merged**
